Closures are Copy only if their captures are
Closures are no longer automatically Copy unless that's safe.

Exception: If we don't know the type of the still-generic environment
yet we default to Copy.

Fix closure calls to borrow, not move the closure.